"""align schema metadata comments

Revision ID: 9616b2eaa448
Revises: 20260711_0012
Create Date: 2026-07-13 10:05:27.999794+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9616b2eaa448'
down_revision: str | Sequence[str] | None = '20260711_0012'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_shares', 'id',
               existing_type=sa.UUID(),
               comment='分享 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('conversation_shares', 'conversation_id',
               existing_type=sa.UUID(),
               comment='来源对话 ID。',
               existing_nullable=False)
    op.alter_column('conversation_shares', 'owner_id',
               existing_type=sa.UUID(),
               comment='创建分享的用户 ID。',
               existing_nullable=False)
    op.alter_column('conversation_shares', 'title',
               existing_type=sa.TEXT(),
               comment='分享标题。',
               existing_nullable=False)
    op.alter_column('conversation_shares', 'variant',
               existing_type=sa.TEXT(),
               comment='分享类型：summary 摘要、full-record 完整记录、expert-review 专家复核。',
               existing_nullable=False,
               existing_server_default=sa.text("'summary'::text"))
    op.alter_column('conversation_shares', 'status',
               existing_type=sa.TEXT(),
               comment='分享状态：active 有效、revoked 已撤销、deleted 已删除。',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('conversation_shares', 'view_count',
               existing_type=sa.BIGINT(),
               comment='公开链接访问次数。',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('conversation_shares', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='分享扩展信息。',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversation_shares', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_shares', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_shares', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='分享过期时间，空表示不过期。',
               existing_nullable=True)
    op.alter_column('conversation_shares', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='分享撤销时间。',
               existing_nullable=True)
    op.alter_column('conversation_tags', 'id',
               existing_type=sa.UUID(),
               comment='标签 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('conversation_tags', 'conversation_id',
               existing_type=sa.UUID(),
               comment='所属对话 ID。',
               existing_nullable=False)
    op.alter_column('conversation_tags', 'name',
               existing_type=sa.TEXT(),
               comment='标签名称。',
               existing_nullable=False)
    op.alter_column('conversation_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               comment='对话 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               comment='对话所属用户 ID。',
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.TEXT(),
               comment='对话标题。',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('conversations', 'summary',
               existing_type=sa.TEXT(),
               comment='对话摘要。',
               existing_nullable=True)
    op.alter_column('conversations', 'conversation_type',
               existing_type=sa.TEXT(),
               comment='对话类型：diagnosis 问诊、video 视频咨询、general 普通对话。',
               existing_nullable=False,
               existing_server_default=sa.text("'diagnosis'::text"))
    op.alter_column('conversations', 'status',
               existing_type=sa.TEXT(),
               comment='对话状态：active 正常、archived 归档、deleted 已删除。',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('conversations', 'last_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最近一条消息时间，用于对话列表排序。',
               existing_nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'pinned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Pinned timestamp; null means not pinned.',
               existing_nullable=True)
    op.alter_column('conversations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='软删除时间，未删除时为空。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'id',
               existing_type=sa.UUID(),
               comment='诊断 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('diagnoses', 'user_id',
               existing_type=sa.UUID(),
               comment='诊断所属用户 ID。',
               existing_nullable=False)
    op.alter_column('diagnoses', 'conversation_id',
               existing_type=sa.UUID(),
               comment='关联对话 ID。',
               existing_nullable=False)
    op.alter_column('diagnoses', 'trigger_message_id',
               existing_type=sa.UUID(),
               comment='触发本次诊断的消息 ID。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'status',
               existing_type=sa.TEXT(),
               comment='诊断状态：pending 待处理、running 处理中、completed 完成、failed 失败。',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('diagnoses', 'disease_name',
               existing_type=sa.TEXT(),
               comment='诊断出的疾病名称。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='诊断置信度，范围 0 到 1。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'result_summary',
               existing_type=sa.TEXT(),
               comment='诊断结果摘要。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'suggestion',
               existing_type=sa.TEXT(),
               comment='处置建议。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'follow_up_question',
               existing_type=sa.TEXT(),
               comment='需要继续追问的问题。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'model_name',
               existing_type=sa.TEXT(),
               comment='生成诊断结果的模型名称。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnoses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnoses', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='诊断完成时间。',
               existing_nullable=True)
    op.alter_column('diagnosis_evidence', 'id',
               existing_type=sa.UUID(),
               comment='诊断依据 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('diagnosis_evidence', 'diagnosis_id',
               existing_type=sa.UUID(),
               comment='所属诊断 ID。',
               existing_nullable=False)
    op.alter_column('diagnosis_evidence', 'evidence_type',
               existing_type=sa.TEXT(),
               comment='依据类型：symptom 症状、rag_document 文档、graph_path 图谱路径、rule 规则、image 图片。',
               existing_nullable=False)
    op.alter_column('diagnosis_evidence', 'title',
               existing_type=sa.TEXT(),
               comment='依据标题。',
               existing_nullable=False)
    op.alter_column('diagnosis_evidence', 'content',
               existing_type=sa.TEXT(),
               comment='依据内容。',
               existing_nullable=False)
    op.alter_column('diagnosis_evidence', 'source',
               existing_type=sa.TEXT(),
               comment='依据来源。',
               existing_nullable=True)
    op.alter_column('diagnosis_evidence', 'score',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='依据分数或相关性得分。',
               existing_nullable=True)
    op.alter_column('diagnosis_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnosis_multimodal_analyses', 'id',
               existing_type=sa.UUID(),
               comment='多模态解析 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('diagnosis_multimodal_analyses', 'conversation_id',
               existing_type=sa.UUID(),
               comment='关联问诊对话 ID。',
               existing_nullable=False)
    op.alter_column('diagnosis_multimodal_analyses', 'message_id',
               existing_type=sa.UUID(),
               comment='触发解析的用户消息 ID。',
               existing_nullable=False)
    op.alter_column('diagnosis_multimodal_analyses', 'status',
               existing_type=sa.TEXT(),
               comment='解析状态：pending 待处理、running 处理中、completed 完成、failed 失败。',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('diagnosis_multimodal_analyses', 'model_id',
               existing_type=sa.TEXT(),
               comment='执行多模态解析的模型 ID。',
               existing_nullable=True)
    op.alter_column('diagnosis_multimodal_analyses', 'error_message',
               existing_type=sa.TEXT(),
               comment='解析失败原因。',
               existing_nullable=True)
    op.alter_column('diagnosis_multimodal_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnosis_multimodal_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('files', 'id',
               existing_type=sa.UUID(),
               comment='文件 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('files', 'user_id',
               existing_type=sa.UUID(),
               comment='上传用户 ID。',
               existing_nullable=False)
    op.alter_column('files', 'project_id',
               existing_type=sa.UUID(),
               comment='所属项目 ID。为空表示未归入项目。',
               existing_nullable=True)
    op.alter_column('files', 'file_name',
               existing_type=sa.TEXT(),
               comment='原始文件名。',
               existing_nullable=False)
    op.alter_column('files', 'file_type',
               existing_type=sa.TEXT(),
               comment='文件类型：image、video、document、audio、other。',
               existing_nullable=False)
    op.alter_column('files', 'mime_type',
               existing_type=sa.TEXT(),
               comment='文件 MIME 类型。',
               existing_nullable=False)
    op.alter_column('files', 'storage_key',
               existing_type=sa.TEXT(),
               comment='对象存储 key 或本地存储 key。',
               existing_nullable=False)
    op.alter_column('files', 'storage_url',
               existing_type=sa.TEXT(),
               comment='可访问文件 URL。',
               existing_nullable=True)
    op.alter_column('files', 'file_size',
               existing_type=sa.BIGINT(),
               comment='文件大小，单位字节。',
               existing_nullable=False)
    op.alter_column('files', 'checksum',
               existing_type=sa.TEXT(),
               comment='文件校验值，用于去重或完整性校验。',
               existing_nullable=True)
    op.alter_column('files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('files', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='软删除时间，未删除时为空。',
               existing_nullable=True)
    op.alter_column('message_files', 'id',
               existing_type=sa.UUID(),
               comment='消息文件关联 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('message_files', 'message_id',
               existing_type=sa.UUID(),
               comment='消息 ID。',
               existing_nullable=False)
    op.alter_column('message_files', 'file_id',
               existing_type=sa.UUID(),
               comment='文件 ID。',
               existing_nullable=False)
    op.alter_column('message_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               comment='消息 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               comment='所属对话 ID。',
               existing_nullable=False)
    op.alter_column('messages', 'sender_type',
               existing_type=sa.TEXT(),
               comment='发送方类型：user 用户、assistant 助手、system 系统。',
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment='消息文本内容。纯文件消息可为空字符串。',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('messages', 'message_type',
               existing_type=sa.TEXT(),
               comment='消息类型：text 文本、image 图片、video 视频、file 文件、diagnosis_result 诊断结果。',
               existing_nullable=False,
               existing_server_default=sa.text("'text'::text"))
    op.alter_column('messages', 'status',
               existing_type=sa.TEXT(),
               comment='消息状态：sending 发送中、sent 已发送、failed 失败。',
               existing_nullable=False,
               existing_server_default=sa.text("'sent'::text"))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='软删除时间，未删除时为空。',
               existing_nullable=True)
    op.alter_column('project_shares', 'id',
               existing_type=sa.UUID(),
               comment='分享 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('project_shares', 'project_id',
               existing_type=sa.UUID(),
               comment='来源项目 ID。',
               existing_nullable=False)
    op.alter_column('project_shares', 'owner_id',
               existing_type=sa.UUID(),
               comment='创建分享的用户 ID。',
               existing_nullable=False)
    op.alter_column('project_shares', 'title',
               existing_type=sa.TEXT(),
               comment='分享标题。',
               existing_nullable=False)
    op.alter_column('project_shares', 'variant',
               existing_type=sa.TEXT(),
               comment='分享类型：summary 摘要、full-record 完整记录、expert-review 专家复核。',
               existing_nullable=False,
               existing_server_default=sa.text("'summary'::text"))
    op.alter_column('project_shares', 'status',
               existing_type=sa.TEXT(),
               comment='分享状态：active 有效、revoked 已撤销、deleted 已删除。',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('project_shares', 'view_count',
               existing_type=sa.BIGINT(),
               comment='公开链接访问次数。',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('project_shares', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='分享扩展信息。',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('project_shares', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_shares', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_shares', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='分享过期时间，空表示不过期。',
               existing_nullable=True)
    op.alter_column('project_shares', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='分享撤销时间。',
               existing_nullable=True)
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               comment='项目 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('projects', 'owner_id',
               existing_type=sa.UUID(),
               comment='项目创建人用户 ID。',
               existing_nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.TEXT(),
               comment='项目名称。',
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               comment='项目描述。',
               existing_nullable=True)
    op.alter_column('projects', 'icon_key',
               existing_type=sa.TEXT(),
               comment='项目图标 key，对应前端图标选择。',
               existing_nullable=False,
               existing_server_default=sa.text("'folder'::text"))
    op.alter_column('projects', 'color',
               existing_type=sa.TEXT(),
               comment='项目颜色值，对应前端颜色选择。',
               existing_nullable=False,
               existing_server_default=sa.text("'#11110f'::text"))
    op.alter_column('projects', 'status',
               existing_type=sa.TEXT(),
               comment='项目状态：active 正常、archived 归档、deleted 已删除。',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'pinned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Pinned timestamp; null means not pinned.',
               existing_nullable=True)
    op.alter_column('projects', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='软删除时间，未删除时为空。',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='软删除时间，未删除时为空。',
               existing_nullable=True)
    op.alter_column('projects', 'pinned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Pinned timestamp; null means not pinned.',
               existing_nullable=True)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='项目状态：active 正常、archived 归档、deleted 已删除。',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('projects', 'color',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='项目颜色值，对应前端颜色选择。',
               existing_nullable=False,
               existing_server_default=sa.text("'#11110f'::text"))
    op.alter_column('projects', 'icon_key',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='项目图标 key，对应前端图标选择。',
               existing_nullable=False,
               existing_server_default=sa.text("'folder'::text"))
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='项目描述。',
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='项目名称。',
               existing_nullable=False)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='项目创建人用户 ID。',
               existing_nullable=False)
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='项目 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('project_shares', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='分享撤销时间。',
               existing_nullable=True)
    op.alter_column('project_shares', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='分享过期时间，空表示不过期。',
               existing_nullable=True)
    op.alter_column('project_shares', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_shares', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_shares', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='分享扩展信息。',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('project_shares', 'view_count',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='公开链接访问次数。',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('project_shares', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='分享状态：active 有效、revoked 已撤销、deleted 已删除。',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('project_shares', 'variant',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='分享类型：summary 摘要、full-record 完整记录、expert-review 专家复核。',
               existing_nullable=False,
               existing_server_default=sa.text("'summary'::text"))
    op.alter_column('project_shares', 'title',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='分享标题。',
               existing_nullable=False)
    op.alter_column('project_shares', 'owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='创建分享的用户 ID。',
               existing_nullable=False)
    op.alter_column('project_shares', 'project_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='来源项目 ID。',
               existing_nullable=False)
    op.alter_column('project_shares', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='分享 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('messages', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='软删除时间，未删除时为空。',
               existing_nullable=True)
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='消息状态：sending 发送中、sent 已发送、failed 失败。',
               existing_nullable=False,
               existing_server_default=sa.text("'sent'::text"))
    op.alter_column('messages', 'message_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='消息类型：text 文本、image 图片、video 视频、file 文件、diagnosis_result 诊断结果。',
               existing_nullable=False,
               existing_server_default=sa.text("'text'::text"))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='消息文本内容。纯文件消息可为空字符串。',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('messages', 'sender_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='发送方类型：user 用户、assistant 助手、system 系统。',
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属对话 ID。',
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='消息 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('message_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_files', 'file_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='文件 ID。',
               existing_nullable=False)
    op.alter_column('message_files', 'message_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='消息 ID。',
               existing_nullable=False)
    op.alter_column('message_files', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='消息文件关联 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('files', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='软删除时间，未删除时为空。',
               existing_nullable=True)
    op.alter_column('files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('files', 'checksum',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='文件校验值，用于去重或完整性校验。',
               existing_nullable=True)
    op.alter_column('files', 'file_size',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='文件大小，单位字节。',
               existing_nullable=False)
    op.alter_column('files', 'storage_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='可访问文件 URL。',
               existing_nullable=True)
    op.alter_column('files', 'storage_key',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='对象存储 key 或本地存储 key。',
               existing_nullable=False)
    op.alter_column('files', 'mime_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='文件 MIME 类型。',
               existing_nullable=False)
    op.alter_column('files', 'file_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='文件类型：image、video、document、audio、other。',
               existing_nullable=False)
    op.alter_column('files', 'file_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='原始文件名。',
               existing_nullable=False)
    op.alter_column('files', 'project_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属项目 ID。为空表示未归入项目。',
               existing_nullable=True)
    op.alter_column('files', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='上传用户 ID。',
               existing_nullable=False)
    op.alter_column('files', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='文件 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('diagnosis_multimodal_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnosis_multimodal_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnosis_multimodal_analyses', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='解析失败原因。',
               existing_nullable=True)
    op.alter_column('diagnosis_multimodal_analyses', 'model_id',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='执行多模态解析的模型 ID。',
               existing_nullable=True)
    op.alter_column('diagnosis_multimodal_analyses', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='解析状态：pending 待处理、running 处理中、completed 完成、failed 失败。',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('diagnosis_multimodal_analyses', 'message_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='触发解析的用户消息 ID。',
               existing_nullable=False)
    op.alter_column('diagnosis_multimodal_analyses', 'conversation_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联问诊对话 ID。',
               existing_nullable=False)
    op.alter_column('diagnosis_multimodal_analyses', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='多模态解析 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('diagnosis_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnosis_evidence', 'score',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='依据分数或相关性得分。',
               existing_nullable=True)
    op.alter_column('diagnosis_evidence', 'source',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='依据来源。',
               existing_nullable=True)
    op.alter_column('diagnosis_evidence', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='依据内容。',
               existing_nullable=False)
    op.alter_column('diagnosis_evidence', 'title',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='依据标题。',
               existing_nullable=False)
    op.alter_column('diagnosis_evidence', 'evidence_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='依据类型：symptom 症状、rag_document 文档、graph_path 图谱路径、rule 规则、image 图片。',
               existing_nullable=False)
    op.alter_column('diagnosis_evidence', 'diagnosis_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属诊断 ID。',
               existing_nullable=False)
    op.alter_column('diagnosis_evidence', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='诊断依据 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('diagnoses', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='诊断完成时间。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnoses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnoses', 'model_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='生成诊断结果的模型名称。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'follow_up_question',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='需要继续追问的问题。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'suggestion',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='处置建议。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'result_summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='诊断结果摘要。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='诊断置信度，范围 0 到 1。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'disease_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='诊断出的疾病名称。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='诊断状态：pending 待处理、running 处理中、completed 完成、failed 失败。',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('diagnoses', 'trigger_message_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='触发本次诊断的消息 ID。',
               existing_nullable=True)
    op.alter_column('diagnoses', 'conversation_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联对话 ID。',
               existing_nullable=False)
    op.alter_column('diagnoses', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='诊断所属用户 ID。',
               existing_nullable=False)
    op.alter_column('diagnoses', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='诊断 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('conversations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='软删除时间，未删除时为空。',
               existing_nullable=True)
    op.alter_column('conversations', 'pinned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Pinned timestamp; null means not pinned.',
               existing_nullable=True)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'last_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最近一条消息时间，用于对话列表排序。',
               existing_nullable=True)
    op.alter_column('conversations', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='对话状态：active 正常、archived 归档、deleted 已删除。',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('conversations', 'conversation_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='对话类型：diagnosis 问诊、video 视频咨询、general 普通对话。',
               existing_nullable=False,
               existing_server_default=sa.text("'diagnosis'::text"))
    op.alter_column('conversations', 'summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='对话摘要。',
               existing_nullable=True)
    op.alter_column('conversations', 'title',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='对话标题。',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='对话所属用户 ID。',
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='对话 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('conversation_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_tags', 'name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='标签名称。',
               existing_nullable=False)
    op.alter_column('conversation_tags', 'conversation_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属对话 ID。',
               existing_nullable=False)
    op.alter_column('conversation_tags', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='标签 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('conversation_shares', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='分享撤销时间。',
               existing_nullable=True)
    op.alter_column('conversation_shares', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='分享过期时间，空表示不过期。',
               existing_nullable=True)
    op.alter_column('conversation_shares', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录最后更新时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_shares', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间。',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_shares', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='分享扩展信息。',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversation_shares', 'view_count',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='公开链接访问次数。',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('conversation_shares', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='分享状态：active 有效、revoked 已撤销、deleted 已删除。',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('conversation_shares', 'variant',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='分享类型：summary 摘要、full-record 完整记录、expert-review 专家复核。',
               existing_nullable=False,
               existing_server_default=sa.text("'summary'::text"))
    op.alter_column('conversation_shares', 'title',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='分享标题。',
               existing_nullable=False)
    op.alter_column('conversation_shares', 'owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='创建分享的用户 ID。',
               existing_nullable=False)
    op.alter_column('conversation_shares', 'conversation_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='来源对话 ID。',
               existing_nullable=False)
    op.alter_column('conversation_shares', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='分享 ID。',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###
